[project]
name = "headline-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "xiaomao", email = "ychenliao@163.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.142.2",
    "pydantic-settings>=2.15.0",
    "pyyaml>=6.0.3",
    "uvicorn>=0.54.0",
]

[project.scripts]
headline-backend = "headline_backend:main"

[[tool.uv.index]]
url = "https://uv.agentsmirror.com/pypi/simple"
default = true

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
